version: "3"

volumes:
  db-data:
  images:
  extensions:

services:
  db:
    image: "mariadb"
    environment:
      - MYSQL_DATABASE=wiki
      - MYSQL_USER=wiki
      - MYSQL_PASSWORD=i-milleuno-nomi-di-mallllco
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql
  mediawiki:
    image: "ghcr.io/ryghub/mediawiki-rygwiki:latest"
    ports:
      - "30068:80"
    links:
      - db
    volumes:
      - images:/var/www/html/images
      - extensions:/var/www/mediawiki/extensions
      - ./html:/var/www/html/
      - ./mediawiki:/var/www/mediawiki/
